prueba2

diff --git a/Dockerfile.deploy b/Dockerfile.deploy
--- a/Dockerfile.deploy
+++ b/Dockerfile.deploy
@@ -12,12 +12,19 @@ COPY . .
 
 # Angular Environment Variable Injection (Build-time)
 # Replace the placeholder in environment.prod.ts
+#ARG API_URL=http://localhost:8081/api
+#RUN echo "Inyectando API_URL: ${API_URL}" && \
+#    sed -i "s|apiUrl:.*|apiUrl: '${API_URL}'|g" src/environments/environment.prod.ts && \
+#    echo "Contenido de environment.prod.ts corregido:" && \
+#    cat src/environments/environment.prod.ts && \
+#    grep -q "${API_URL}" src/environments/environment.prod.ts || (echo "ERROR: No se inyectó la URL correctamente" && exit 1)
+
 ARG API_URL=http://localhost:8081/api
 RUN echo "Inyectando API_URL: ${API_URL}" && \
     sed -i "s|apiUrl:.*|apiUrl: '${API_URL}'|g" src/environments/environment.prod.ts && \
     echo "Contenido de environment.prod.ts corregido:" && \
     cat src/environments/environment.prod.ts && \
-    grep -q "${API_URL}" src/environments/environment.prod.ts || (echo "ERROR: No se inyectó la URL correctamente" && exit 1)
+    grep -q "'${API_URL}'" src/environments/environment.prod.ts || (echo "ERROR CRÍTICO: La URL no se inyectó en environment.prod.ts" && exit 1)
 
 # Build for production
 RUN npm run build -- --configuration production
